mod_init_medium Module Reference
mod_init_medium Module Reference
This module contains subroutines to initialize medium for hexahedron and quadrangle elements. It also contains subroutines to write medium in binary VTK xml format readable by ParaView.
Public Member Functions
subroutine, public init_hexa_medium ()
This subroutine fills medium properties (elastic or viscoelastic) at GLL nodes of hexahedron elements based on material number found in file *.inp generated by CUBIT mesh generator. If files *.cpu.*.mat are present in the simulation's directory, then material number of hexahedron elements are read from files *.cpu*.mat.
subroutine, public init_quadp_medium ()
This subroutine fills medium properties at GLL nodes of paraxial quadrangle elements (i.e., absorbing boundary) based on material number of hexahedron elements it belongs.
Private Member Functions
subroutine, private init_medium_from_mat_file (il_mat_num_of_hexa)
This subroutine fills medium properties at GLL nodes of hexahedron elements based on material number in files *.cpu*.mat.
subroutine, private write_medium_vtk_cell_xml ()
This subroutine writes S and P-wave velocities of the physical domain of cpu myrank in UnstructuredGrid binary vtk_cell xml file readable by ParaView.
subroutine, private write_medium_vtk_node_xml ()
This subroutine writes S and P-wave velocities of the physical domain of cpu myrank in UnstructuredGrid binary vtk_node xml file readable by ParaView.
subroutine, private write_medium_collection ()
This subroutine writes a VTK xml collection file *.pvd which contains all *.vtu files generated by write_medium_vtk_cell_xml or write_medium_vtk_node_xml.
Detailed Description
Definition at line 111 of file module_init_medium.f90.
Member Function/Subroutine Documentation
subroutine, public mod_init_medium::init_hexa_medium ()
Returns
mod_global_variables::rg_hexa_gll_rho
mod_global_variables::rg_hexa_gll_rhovs2
mod_global_variables::rg_hexa_gll_rhovp2
mod_global_variables::rg_hexa_gll_wkqs
mod_global_variables::rg_hexa_gll_wkqp
mod_global_variables::rg_mem_var_exp
mod_global_variables::tg_elastic_material
mod_global_variables::tg_viscoelastic_material
Definition at line 143 of file module_init_medium.f90.
References init_medium_from_mat_file(), and write_medium_vtk_cell_xml().
Referenced by efispec3d().
subroutine, private mod_init_medium::init_medium_from_mat_file (integer, dimension(:), intent(out) il_mat_num_of_hexa) private
Parameters
il_mat_num_of_hexa : array filled with material number of hexahedron elements in cpu myrank.
Definition at line 533 of file module_init_medium.f90.
Referenced by init_hexa_medium().
subroutine, public mod_init_medium::init_quadp_medium ()
Returns
mod_global_variables::rg_quadp_gll_rhovs
mod_global_variables::rg_quadp_gll_rhovp
Definition at line 414 of file module_init_medium.f90.
Referenced by efispec3d().
subroutine, private mod_init_medium::write_medium_collection () private
Returns
files *.medium.collection.pvd
Definition at line 854 of file module_init_medium.f90.
Referenced by write_medium_vtk_cell_xml(), and write_medium_vtk_node_xml().
subroutine, private mod_init_medium::write_medium_vtk_cell_xml () private
Returns
files *.vtu
Definition at line 566 of file module_init_medium.f90.
References mod_vtk_io::vtk_con_xml(), mod_vtk_io::vtk_dat_xml(), mod_vtk_io::vtk_end_xml(), mod_vtk_io::vtk_ini_xml(), and write_medium_collection().
Referenced by init_hexa_medium().
subroutine, private mod_init_medium::write_medium_vtk_node_xml () private
Returns
files *.vtu
Definition at line 701 of file module_init_medium.f90.
References mod_vtk_io::vtk_con_xml(), mod_vtk_io::vtk_dat_xml(), mod_vtk_io::vtk_end_xml(), mod_vtk_io::vtk_ini_xml(), and write_medium_collection().
The documentation for this module was generated from the following file:
module_init_medium.f90