mod_jacobian Module Reference
mod_jacobian Module Reference
This module contains subroutines to compute jacobian matrix.
Public Member Functions
subroutine, public compute_hexa_jacobian (ihexa, xisol, etsol, zesol, dxidx, dxidy, dxidz, detdx, detdy, detdz, dzedx, dzedy, dzedz, det)
This subroutine computes jacobian matrix and its determinant at location \(\xi,\eta,\zeta\) in hexahedron element ihexa.
subroutine, public compute_quad_jacobian (iquad, xisol, etsol, dxidx, dxidy, detdx, detdy, det)
This subroutine computes jacobian matrix and its determinant at location \(\xi,\eta\) in quadrangle element iquad.
Detailed Description
Definition at line 111 of file module_jacobian.f90.
Member Function/Subroutine Documentation
subroutine, public mod_jacobian::compute_hexa_jacobian (integer, intent(in) ihexa, real, intent(in) xisol, real, intent(in) etsol, real, intent(in) zesol, real, intent(out) dxidx, real, intent(out) dxidy, real, intent(out) dxidz, real, intent(out) detdx, real, intent(out) detdy, real, intent(out) detdz, real, intent(out) dzedx, real, intent(out) dzedy, real, intent(out) dzedz, real, intent(out) det)
Parameters
ihexa : hexahedron element number in cpu myrank
xisol : \(\xi \) local coordinate where to compute jacobian matrix and its determinant
etsol : \(\eta \) local coordinate where to compute jacobian matrix and its determinant
zesol : \(\zeta\) local coordinate where to compute jacobian matrix and its determinant
dxidx : \(\frac{\partial \xi }{\partial x}\)
dxidy : \(\frac{\partial \xi }{\partial y}\)
dxidz : \(\frac{\partial \xi }{\partial z}\)
detdx : \(\frac{\partial \eta }{\partial x}\)
detdy : \(\frac{\partial \eta }{\partial y}\)
detdz : \(\frac{\partial \eta }{\partial z}\)
dzedx : \(\frac{\partial \zeta}{\partial x}\)
dzedy : \(\frac{\partial \zeta}{\partial y}\)
dzedz : \(\frac{\partial \zeta}{\partial z}\)
det : determinant of jacobian matrix
Definition at line 143 of file module_jacobian.f90.
References mod_lagrange::lagrad_geom(), and mod_lagrange::lagrap_geom().
Referenced by mod_receiver::compute_info_hexa_receiver(), mod_source::compute_source_local_coordinate(), and mod_init_efi::init_jacobian_matrix_hexa().
subroutine, public mod_jacobian::compute_quad_jacobian (integer, intent(in) iquad, real, intent(in) xisol, real, intent(in) etsol, real, intent(out) dxidx, real, intent(out) dxidy, real, intent(out) detdx, real, intent(out) detdy, real det)
Parameters
iquad : quadrangle element number in cpu myrank
xisol : \(\xi \) local coordinate where to compute jacobian matrix and its determinant
etsol : \(\eta \) local coordinate where to compute jacobian matrix and its determinant
dxidx : \(\frac{\partial \xi }{\partial x}\)
dxidy : \(\frac{\partial \xi }{\partial y}\)
detdx : \(\frac{\partial \eta }{\partial x}\)
detdy : \(\frac{\partial \eta }{\partial y}\)
det : determinant of jacobian matrix
Definition at line 290 of file module_jacobian.f90.
References mod_lagrange::lagrad_geom(), and mod_lagrange::lagrap_geom().
Referenced by mod_receiver::compute_info_quad_receiver().
The documentation for this module was generated from the following file:
module_jacobian.f90