mod_snapshot Module Reference
mod_snapshot Module Reference
This module contains subroutines to compute and write snapshots of the free surface (either in GMT or VTK xml formats).
Public Member Functions
subroutine, public init_snapshot ()
This subroutine generates a structured grid of receivers on the free surface.
subroutine, public write_snapshot ()
This subroutine computes and writes \(x,y,z\)-displacements, velocities and accelerations at receivers used for free surface snapshots.
subroutine, public write_collection_vtk ()
This subroutine selects which ParaView collection files should be written (displacement, velocity and/or acceleration collections) depending on value of variables mod_global_variables::lg_snapshot_displacement, mod_global_variables::lg_snapshot_velocity and mod_global_variables::lg_snapshot_acceleration.
subroutine, public write_peak_ground_motion ()
This subroutine writes peak ground motions files in GMT or VTK formats.
Private Member Functions
subroutine, private write_snapshot_gmt_native_format (fname, val)
This subroutine writes structured grid snapshot in binary native GMT format.
subroutine, private write_header_gmt_native_format (desc, nx, ny, x_min, x_max, y_min, y_max, z_min, z_max, x_inc, y_inc)
This subroutine writes header of binary native GMT files.
subroutine, private write_snapshot_vtk (fname, varname, valx, valy, valz)
This subroutine writes structured grid snapshot in binary VTK xml format.
subroutine, private collection_vtk (varname)
This subroutine write Paraview collection file *.pvd of VTK xml snapshot files *.vts.
Detailed Description
Definition at line 111 of file module_snapshot.f90.
Member Function/Subroutine Documentation
subroutine, private mod_snapshot::collection_vtk (character(len=*), intent(in) varname) private
Parameters
varname : variable name
Definition at line 1189 of file module_snapshot.f90.
Referenced by write_collection_vtk().
subroutine, public mod_snapshot::init_snapshot ()
Returns
mod_global_variables::tg_receiver_snapshot_quad : information about receivers' used for snapshots in cpu myrank. See mod_global_variables::type_receiver_quad
mod_global_variables::rg_receiver_snapshot_z : \(z\)-coordinate of receivers' used for snapshots
Definition at line 135 of file module_snapshot.f90.
References mod_receiver::compute_info_quad_receiver(), and mod_receiver::search_closest_quad_gll().
Referenced by efispec3d().
subroutine, private mod_snapshot::write_header_gmt_native_format (integer, intent(in) desc, integer, intent(in) nx, integer, intent(in) ny, real, intent(in) x_min, real, intent(in) x_max, real, intent(in) y_min, real, intent(in) y_max, real, intent(in) z_min, real, intent(in) z_max, real, intent(in) x_inc, real, intent(in) y_inc) private
Parameters
desc : mpi_unit of the file
nx : number of receivers along \(x\)-direction
ny : number of receivers along \(y\)-direction
x_min : minimum \(x\)-coordinate
x_max : maximum \(x\)-coordinate
y_min : minimum \(y\)-coordinate
y_max : maximum \(y\)-coordinate
z_min : minimum \(z\)-coordinate
z_max : maximum \(z\)-coordinate
x_inc : \(x\)-increment between receivers
y_inc : \(y\)-increment between receivers
Definition at line 768 of file module_snapshot.f90.
Referenced by write_snapshot_gmt_native_format().
subroutine, public mod_snapshot::write_snapshot ()
Returns
Snapshots are written in binary native GMT format and/or in binary VTK xml format.
Definition at line 453 of file module_snapshot.f90.
References mod_gll_value::get_quad_gll_value(), mod_lagrange::quad_lagrange_interp(), write_snapshot_gmt_native_format(), and write_snapshot_vtk().
Referenced by efispec3d().
subroutine, private mod_snapshot::write_snapshot_gmt_native_format (character(len=255), intent(in) fname, real, dimension(ig_nreceiver_snapshot), intent(in) val) private
Parameters
fname : file name of the snapshot
val : values to be written
Definition at line 643 of file module_snapshot.f90.
References write_header_gmt_native_format().
Referenced by write_peak_ground_motion(), and write_snapshot().
subroutine, private mod_snapshot::write_snapshot_vtk (character(len=255), intent(in) fname, character(len= 4), intent(in) varname, real, dimension(ig_nreceiver_snapshot), intent(in) valx, real, dimension(ig_nreceiver_snapshot), intent(in) valy, real, dimension(ig_nreceiver_snapshot), intent(in) valz) private
Parameters
fname : file name of the snapshot
varname : variable name
valx : \(x\)-direction values
valy : \(y\)-direction values
valz : \(z\)-direction values
Definition at line 897 of file module_snapshot.f90.
References mod_vtk_io::vtk_dat_xml(), mod_vtk_io::vtk_end_xml(), and mod_vtk_io::vtk_ini_xml().
Referenced by write_peak_ground_motion(), and write_snapshot().
The documentation for this module was generated from the following file:
module_snapshot.f90