mod_init_efi Module Reference
mod_init_efi Module Reference
This module contains subroutines to initialize some global variable vectors and matrices.
Public Member Functions
subroutine, public init_mpi ()
This subroutine initializes MPI.
subroutine, public init_input_variables ()
This subroutine initializes the simulation by writing header of listing file *.lst and reading variables of configuration file *.cfg.
subroutine, public init_gll_nodes ()
This subroutine computes GLL nodes abscissa and weight in the reference domain [-1:1] as well as derivative of Lagrange polynomials at GLL nodes.
subroutine, public init_gll_nodes_coordinates ()
This subroutine computes GLL nodes \(x,y,z\)-coordinates in the physical domain, cartesian right-handed coordinate system.
subroutine, public init_mass_matrix ()
This subroutine computes and assembles the mass matrix \(M\) of the system \(M\ddot{U} + C\dot{U} + KU = F^{ext} \).
subroutine, public init_jacobian_matrix_hexa ()
This subroutine computes Jacobian matrix and its determinant for hexahedron elements.
subroutine, public init_jacobian_matrix_quad ()
This subroutine computes the determinant of Jacobian matrix and normal unit vector of quadrangle elements.
Detailed Description
Definition at line 111 of file module_init_efi.f90.
Member Function/Subroutine Documentation
subroutine, public mod_init_efi::init_gll_nodes ()
Reference
C. Canuto, M. Y. Hussaini, A. Quarteroni, T. A. Tang, "Spectral Methods in Fluid Dynamics," Section 2.3. Springer-Verlag 1987
Authors
Initially written for Matlab by G. von Winckel - 04/17/2004. Translated in FORTRAN for EFISPEC3D by F. De Martin
Returns
mod_global_variables::rg_gll_abscissa : GLL node coordinates \(\xi,\eta,\zeta\) in the reference domain [-1:1]
mod_global_variables::rg_gll_weight : GLL node weights
mod_global_variables::rg_gll_lagrange_deriv : derivative of Lagrange polynomials at GLL nodes
mod_global_variables::rg_gll_abscissa_dist : inverse of distance between GLL nodes
Definition at line 524 of file module_init_efi.f90.
References mod_lagrange::lagrad().
Referenced by efispec3d().
subroutine, public mod_init_efi::init_gll_nodes_coordinates ()
Returns
mod_global_variables::rg_gll_coordinate : GLL nodes \(x,y,z\)-coordinates in cpu myrank
Definition at line 649 of file module_init_efi.f90.
References mod_lagrange::lagrap_geom().
Referenced by efispec3d().
subroutine, public mod_init_efi::init_input_variables ()
Returns
global variables read from file *.cfg needed to initialize a simulation
Definition at line 178 of file module_init_efi.f90.
Referenced by efispec3d().
subroutine, public mod_init_efi::init_jacobian_matrix_hexa ()
Returns
rg_hexa_gll_jacobian_det : determinant of jacobian matrix at GLL nodes of hexahedron elements in cpu myrank
rg_hexa_gll_dxidx : \(\frac{\partial \xi }{\partial x} \) at GLL nodes of hexahedron elements
rg_hexa_gll_dxidy : \(\frac{\partial \xi }{\partial y} \) at GLL nodes of hexahedron elements
rg_hexa_gll_dxidz : \(\frac{\partial \xi }{\partial z} \) at GLL nodes of hexahedron elements
rg_hexa_gll_detdx : \(\frac{\partial \eta }{\partial x} \) at GLL nodes of hexahedron elements
rg_hexa_gll_detdy : \(\frac{\partial \eta }{\partial y} \) at GLL nodes of hexahedron elements
rg_hexa_gll_detdz : \(\frac{\partial \eta }{\partial z} \) at GLL nodes of hexahedron elements
rg_hexa_gll_dzedx : \(\frac{\partial \zeta}{\partial x} \) at GLL nodes of hexahedron elements
rg_hexa_gll_dzedy : \(\frac{\partial \zeta}{\partial y} \) at GLL nodes of hexahedron elements
rg_hexa_gll_dzedz : \(\frac{\partial \zeta}{\partial z} \) at GLL nodes of hexahedron elements
Definition at line 922 of file module_init_efi.f90.
References mod_jacobian::compute_hexa_jacobian(), mod_lagrange::lagrad_geom(), and mod_lagrange::lagrap_geom().
Referenced by efispec3d().
subroutine, public mod_init_efi::init_jacobian_matrix_quad ()
Returns
rg_quadp_gll_jaco_det : determinant of jacobian matrix at GLL nodes of quadrangle elements in cpu myrank
rg_quadp_gll_normal : normal unit vector at GLL nodes of quadrangle elements
Definition at line 1070 of file module_init_efi.f90.
References mod_lagrange::lagrad_geom(), and mod_lagrange::lagrap_geom().
Referenced by efispec3d().
subroutine, public mod_init_efi::init_mass_matrix ()
Returns
mod_global_variables::rg_gll_mass_matrix : diagonal mass matrix in cpu myrank
Definition at line 783 of file module_init_efi.f90.
Referenced by efispec3d().
subroutine, public mod_init_efi::init_mpi ()
Returns
mod_global_variables::ig_ncpu
mod_global_variables::ig_myrank
mod_global_variables::cg_cpu_name
mod_global_variables::ig_cpu_name_len
Definition at line 134 of file module_init_efi.f90.
Referenced by efispec3d().
The documentation for this module was generated from the following file:
module_init_efi.f90