mod_init_mesh Module Reference
mod_init_mesh Module Reference
This module contains subroutines to read mesh files and creates GLL nodes global numbering in cpu myrank.
Public Member Functions
subroutine, public init_mesh ()
This subroutine reads mesh files *.inp for cpu myrank and creates GLL numbering of hexahedron and quadrangle elements for cpu myrank.
Private Member Functions
subroutine, private init_gll_number (ihexa, ngll_total)
This subroutine increments GLL numbering of hexahedron elements in cpu myrank (see variable mod_global_variables::ig_ngll_total) and creates the local to global GLL indirection array mod_global_variables::ig_hexa_gll_glonum for hexahedron elements.
subroutine, private propagate_gll_nodes_quad (ihexa, iface, iquad, global_gll_of_quad, number_of_quad)
This subroutine creates the local to global GLL indirection array for quadrangle elements by propagating existing GLL numbering of hexahedron elements.
subroutine, private propagate_gll_nodes_face (ihexa_old, iface_old, ihexa_new, iface_new, icoty_new)
This subroutine propagates existing GLL numbering of hexahedron elements to the face of its neighbors hexahedron elements.
subroutine, private propagate_gll_nodes_edge (ihexa_old, iedge_old, ihexa_new, iedge_new, icoty_new)
This subroutine propagates existing GLL numbering of hexahedron elements to the edge of its neighbors hexahedron elements.
subroutine, private propagate_gll_nodes_corner (ihexa_old, icorner_old, ihexa_new, icorner_new)
This subroutine propagates existing GLL numbering of hexahedron elements to corner (i.e., vertex) of its neighbors hexahedron elements.
subroutine, private init_element (ilnnhe, ilnnqu)
subroutine to set up convention of hexahedron and quadrangle elements
Private Attributes
integer, parameter buffer_read_size = 8192
size of buffer array to read file *.dat
integer, dimension(buffer_read_size) buffer
buffer array to read file *.dat
Detailed Description
Definition at line 111 of file module_init_mesh.f90.
Member Function/Subroutine Documentation
subroutine, private mod_init_mesh::init_element (integer, intent(in) ilnnhe, integer, intent(in) ilnnqu) private
Parameters
ilnnhe : local name of global variable mod_global_variables::ig_hexa_nnode
ilnnqu : local name of global variable mod_global_variables::ig_quad_nnode
Returns
mod_global_variables::rg_gnode_abscissa
mod_global_variables::rg_gnode_abscissa_dist
mod_global_variables::ig_line_nnode
mod_global_variables::ig_hexa_gnode_xiloc
mod_global_variables::ig_hexa_gnode_etloc
mod_global_variables::ig_hexa_gnode_zeloc
mod_global_variables::ig_quad_gnode_xiloc
mod_global_variables::ig_quad_gnode_etloc
Definition at line 976 of file module_init_mesh.f90.
Referenced by init_mesh().
subroutine, private mod_init_mesh::init_gll_number (integer, intent(in) ihexa, integer, intent(inout) ngll_total) private
Parameters
ihexa : hexahedron element number in cpu myrank
ngll_total : local name of global variable mod_global_variables::ig_ngll_total
Definition at line 513 of file module_init_mesh.f90.
subroutine, public mod_init_mesh::init_mesh ()
Returns
mod_global_variables::ig_mesh_nnode
mod_global_variables::ig_ncpu_neighbor
mod_global_variables::ig_nhexa
mod_global_variables::ig_nhexa_outer
mod_global_variables::ig_nquad_parax
mod_global_variables::ig_nquad_fsurf
mod_global_variables::ig_hexa_nnode
mod_global_variables::ig_quad_nnode
mod_global_variables::rg_mesh_xmax
mod_global_variables::rg_mesh_ymax
mod_global_variables::rg_mesh_zmax
mod_global_variables::rg_mesh_xmin
mod_global_variables::rg_mesh_ymin
mod_global_variables::rg_mesh_zmin
mod_global_variables::rg_gnode_x
mod_global_variables::rg_gnode_y
mod_global_variables::rg_gnode_z
mod_global_variables::ig_ngll_total
mod_global_variables::ig_nneighbor_all_kind
mod_global_variables::tg_cpu_neighbor
mod_global_variables::ig_cpu_neighbor_info
mod_global_variables::ig_hexa_gnode_glonum
mod_global_variables::ig_quadp_gnode_glonum
mod_global_variables::ig_quadf_gnode_glonum
mod_global_variables::ig_hexa_gll_glonum
mod_global_variables::ig_quadp_gll_glonum
mod_global_variables::ig_quadf_gll_glonum
mod_global_variables::ig_quadp_neighbor_hexa
mod_global_variables::ig_quadp_neighbor_hexaface
mod_global_variables::ig_hexa_material_number
Definition at line 167 of file module_init_mesh.f90.
References init_element().
Referenced by efispec3d().
subroutine, private mod_init_mesh::propagate_gll_nodes_corner (integer, intent(in) ihexa_old, integer, intent(in) icorner_old, integer, intent(in) ihexa_new, integer, intent(in) icorner_new) private
Parameters
ihexa_old : hexahedron element already numbered to which ihexa_new is connected
icorner_old : corner number of element ihexa_old to which ihexa_new is connected
ihexa_new : hexahedron element to be numbered connected to ihexa_old
icorner_new : corner number of element ihexa_new connected to icorner_old
Definition at line 897 of file module_init_mesh.f90.
subroutine, private mod_init_mesh::propagate_gll_nodes_edge (integer, intent(in) ihexa_old, integer, intent(in) iedge_old, integer, intent(in) ihexa_new, integer, intent(in) iedge_new, integer, intent(in) icoty_new) private
Parameters
ihexa_old : hexahedron element already numbered to which ihexa_new is connected
iedge_old : edge number of element ihexa_old to which ihexa_new is connected
ihexa_new : hexahedron element to be numbered connected to ihexa_old
iedge_new : edge number of element ihexa_new connected to iedge_old
icoty_new : connexion type to redirect correctly GLL numbering between connected edges of hexahedron elements
Definition at line 798 of file module_init_mesh.f90.
subroutine, private mod_init_mesh::propagate_gll_nodes_face (integer, intent(in) ihexa_old, integer, intent(in) iface_old, integer, intent(in) ihexa_new, integer, intent(in) iface_new, integer, intent(in) icoty_new) private
Parameters
ihexa_old : hexahedron element already numbered to which ihexa_new is connected
iface_old : face number of element ihexa_old to which ihexa_new is connected
ihexa_new : hexahedron element to be numbered connected to ihexa_old
iface_new : face number of element ihexa_new connected to iface_old
icoty_new : connexion type to redirect correctly GLL numbering between connected faces of hexahedron elements
Definition at line 649 of file module_init_mesh.f90.
subroutine, private mod_init_mesh::propagate_gll_nodes_quad (integer, intent(in) ihexa, integer, intent(in) iface, integer, intent(in) iquad, integer, dimension(ig_ngll,ig_ngll,number_of_quad), intent(inout) global_gll_of_quad, integer, intent(in) number_of_quad) private
Parameters
ihexa : hexahedron element number to which iquad is connected
iface : face number of element ihexa to which iquad is connected
iquad : quadrangle element connected to hexahedron element ihexa
global_gll_of_quad : local to global GLL indirection array for quadrangle elements
number_of_quad : number of quadrangle elements in array global_gll_of_quad
Definition at line 560 of file module_init_mesh.f90.
The documentation for this module was generated from the following file:
module_init_mesh.f90