mod_receiver Module Reference
mod_receiver Module Reference
This module contains subroutines to compute information about receivers and to write receivers' time history into binary files.
Public Member Functions
subroutine, public init_hexa_receiver ()
This subroutine reads all receivers in file *.vor; determines to which cpu they belong; computes their local coordinates \(\xi,\eta,\zeta\) in hexahedron elements and open receivers' output files in which displacements, velocities and accelerations are written.
subroutine, public init_quad_receiver ()
This subroutine reads all receivers in file *.fsr; determines to which cpu they belong; computes their local coordinates \(\xi,\eta\) in quadrangle elements and open receivers' output files in which displacements, velocities and accelerations are written.
subroutine, public search_closest_hexa_gll (x, y, z, dmin, kgll, lgll, mgll, iel)
This subroutine searches among all hexahedron elements in cpu myrank the closest GLL node to a point of coordinates \(x,y,z\).
subroutine, public search_closest_quad_gll (x, y, global_gll, dmin, lgll, mgll, iel)
This subroutine searches among all free surface quadrangle elements in cpu myrank the closest GLL node to a point of coordinates \(x,y\).
subroutine, public compute_info_hexa_receiver (tlxinf)
This subroutine computes local coordinates \(\xi,\eta,\zeta\) of a receiver in the hexahedron element it belongs. It also stores global GLL nodes numbers for future interpolations as well as Lagrange polynonial values at the receiver.
subroutine, public compute_info_quad_receiver (tlxinf)
This subroutine computes local coordinates \(\xi,\eta\) of a receiver in the quadrangle element it belongs. It also stores global GLL nodes numbers for future interpolations as well as Lagrange polynonial values at the receiver.
subroutine, public write_receiver_output ()
This subroutine writes \(x,y,z\)-displacements, velocities and accelerations at receivers.
Detailed Description
Definition at line 111 of file module_receiver.f90.
Member Function/Subroutine Documentation
subroutine, public mod_receiver::compute_info_hexa_receiver (type(type_receiver_hexa), intent(inout) tlxinf)
Parameters
tlxinf : data structure for a receiver located inside a hexahedron element
Definition at line 708 of file module_receiver.f90.
References mod_jacobian::compute_hexa_jacobian(), mod_coordinate::compute_hexa_point_coord(), and mod_lagrange::lagrap().
Referenced by init_hexa_receiver().
subroutine, public mod_receiver::compute_info_quad_receiver (type(type_receiver_quad), intent(inout) tlxinf)
Parameters
tlxinf : data structure for a receiver located inside a quadrangle element
Definition at line 842 of file module_receiver.f90.
References mod_jacobian::compute_quad_jacobian(), mod_coordinate::compute_quad_point_coord(), mod_coordinate::compute_quad_point_coord_z(), and mod_lagrange::lagrap().
Referenced by init_quad_receiver(), and mod_snapshot::init_snapshot().
subroutine, public mod_receiver::init_hexa_receiver ()
Returns
mod_global_variables::tg_receiver_hexa
mod_global_variables::ig_nreceiver_hexa
Definition at line 137 of file module_receiver.f90.
References compute_info_hexa_receiver(), and search_closest_hexa_gll().
Referenced by efispec3d().
subroutine, public mod_receiver::init_quad_receiver ()
Returns
mod_global_variables::tg_receiver_quad
mod_global_variables::ig_nreceiver_quad
Definition at line 355 of file module_receiver.f90.
References compute_info_quad_receiver(), and search_closest_quad_gll().
Referenced by efispec3d().
subroutine, public mod_receiver::search_closest_hexa_gll (real, intent(in) x, real, intent(in) y, real, intent(in) z, real, intent(out) dmin, integer, intent(out) kgll, integer, intent(out) lgll, integer, intent(out) mgll, integer, intent(out) iel)
Parameters
x : \(x\)-coordinates of a point
y : \(y\)-coordinates of a point
z : \(z\)-coordinates of a point
dmin : minimal Euclidean distance from point to all GLL nodes in cpu myrank
kgll : closest GLL node index along \(\zeta\)-coordinate
lgll : closest GLL node index along \(\eta \)-coordinate
mgll : closest GLL node index along \(\xi \)-coordinate
iel : number of hexahedron element in cpu myrank whose GLL node has the minimal dmin
Definition at line 576 of file module_receiver.f90.
Referenced by mod_source::init_double_couple_source(), init_hexa_receiver(), and mod_source::init_single_force_source().
subroutine, public mod_receiver::search_closest_quad_gll (real, intent(in) x, real, intent(in) y, integer, dimension(:,:,:), intent(in) global_gll, real, intent(out) dmin, integer, intent(out) lgll, integer, intent(out) mgll, integer, intent(out) iel)
Parameters
x : \(x\)-coordinates of a point
y : \(y\)-coordinates of a point
global_gll : indirection from local GLL nodes to global GLL nodes for quadrangle elements
dmin : minimal Euclidean distance from point to all GLL nodes in cpu myrank
lgll : closest GLL node index along \(\eta \)-coordinate
mgll : closest GLL node index along \(\xi \)-coordinate
iel : number of free surface quadrangle element in cpu myrank whose GLL node has the minimal dmin
Definition at line 647 of file module_receiver.f90.
Referenced by init_quad_receiver(), and mod_snapshot::init_snapshot().
The documentation for this module was generated from the following file:
module_receiver.f90