mod_source Module Reference
mod_source Module Reference
This module contains subroutines to compute information about sources.
Public Member Functions
subroutine, public compute_double_couple_source ()
This subroutine pre-computes all double couple point sources defined by type mod_global_variables::type_double_couple_source as equivalent single force point sources (\(F^{ext}_{n+1} \)) distributed over hexahedron elements (see mod_global_variables::rg_dcsource_gll_force).
subroutine, public init_double_couple_source ()
This subroutine reads all double couple point sources in file *.dcs; sets double couple point sources moment tensor; determines to which cpu belong double couple point sources and computes local coordinates \(\xi,\eta,\zeta\) of double couple point sources inside the hexahedron element it belongs.
subroutine, public init_single_force_source ()
This subroutine reads all single force point sources in file *.sfs; determines to which cpu belong single force point sources and computes local coordinates \(\xi,\eta,\zeta\) of single force point sources inside the hexahedron element it belongs.
Private Member Functions
subroutine, private compute_source_local_coordinate (tlsrc)
This subroutine solves a nonlinear system by a gradient method to compute local coordinates \(\xi,\eta,\zeta\) of a point source inside the hexahedron element it belongs. The starting point of the gradient method is the closest GLL node. Local coordinates are stored in mod_global_variables::tg_dcsource.
Detailed Description
Definition at line 111 of file module_source.f90.
Member Function/Subroutine Documentation
subroutine, public mod_source::compute_double_couple_source ()
Returns
mod_global_variables::rg_dcsource_gll_force
Reference
: Komatitsch and Tromp, 1999 [4]; Komatitsch and Tromp, 2002 [5].
Definition at line 132 of file module_source.f90.
References mod_lagrange::lagrad(), and mod_lagrange::lagrap().
Referenced by efispec3d().
subroutine, private mod_source::compute_source_local_coordinate (type(type_double_couple_source), intent(inout) tlsrc) private
Parameters
tlsrc : data type that contains information about point sources
Definition at line 724 of file module_source.f90.
References mod_jacobian::compute_hexa_jacobian(), and mod_coordinate::compute_hexa_point_coord().
Referenced by init_double_couple_source().
subroutine, public mod_source::init_double_couple_source ()
Returns
mod_global_variables::tg_dcsource
mod_global_variables::ig_ndcsource
mod_global_variables::rg_dcsource_user_func
Definition at line 315 of file module_source.f90.
References compute_source_local_coordinate(), mod_source_function::interp_linear(), and mod_receiver::search_closest_hexa_gll().
Referenced by efispec3d().
subroutine, public mod_source::init_single_force_source ()
Returns
mod_global_variables::tg_sfsource
mod_global_variables::ig_nsfsource
mod_global_variables::rg_sfsource_user_func
Definition at line 533 of file module_source.f90.
References mod_source_function::interp_linear(), and mod_receiver::search_closest_hexa_gll().
Referenced by efispec3d().
The documentation for this module was generated from the following file:
module_source.f90