mod_coordinate Module Reference
mod_coordinate Module Reference
This module contains subroutines to compute global \(x,y,z\)-coordinates of a given point in the physical domain from its local \(\xi,\eta,\zeta\)-coordinates.
Public Member Functions
subroutine, public compute_hexa_point_coord (ihexa, xi, eta, zeta, x, y, z)
subroutine to compute \(x,y,z\)-coordinates of a point knowing to which hexahedron element it belongs and its local coordinates \(\xi,\eta,\zeta\).
subroutine, public compute_quad_point_coord (iquad, xi, eta, x, y, z)
subroutine to compute \(x,y,z\)-coordinates of a point knowing to which quadrangle element it belongs and its local coordinates \(\xi,\eta\).
real function, public compute_quad_point_coord_z (iquad, xi, eta)
function to compute \(z\)-coordinates of a point knowing to which quadrangle element it belongs and its local coordinates \(\xi,\eta\).
Detailed Description
Definition at line 111 of file module_coordinate.f90.
Member Function/Subroutine Documentation
subroutine, public mod_coordinate::compute_hexa_point_coord (integer, intent(in) ihexa, real, intent(in) xi, real, intent(in) eta, real, intent(in) zeta, real, intent(out) x, real, intent(out) y, real, intent(out) z)
Parameters
ihexa,: hexahedron element number in cpu myrank
xi : \(\xi \) local coordinate where to compute global coordinates
eta : \(\eta \) local coordinate where to compute global coordinates
zeta : \(\zeta\) local coordinate where to compute global coordinates
x : \(x\)-coordinate
y : \(y\)-coordinate
z : \(z\)-coordinate
Definition at line 136 of file module_coordinate.f90.
References mod_lagrange::lagrap_geom().
Referenced by mod_receiver::compute_info_hexa_receiver(), and mod_source::compute_source_local_coordinate().
subroutine, public mod_coordinate::compute_quad_point_coord (integer, intent(in) iquad, real, intent(in) xi, real, intent(in) eta, real, intent(out) x, real, intent(out) y, real, intent(out) z)
Parameters
iquad,: quadrangle element number in cpu myrank
xi : \(\xi \) local coordinate where to compute global coordinates
eta : \(\eta \) local coordinate where to compute global coordinates
x : \(x\)-coordinate
y : \(y\)-coordinate
z : \(z\)-coordinate
Definition at line 208 of file module_coordinate.f90.
References mod_lagrange::lagrap_geom().
Referenced by mod_receiver::compute_info_quad_receiver().
real function, public mod_coordinate::compute_quad_point_coord_z (integer, intent(in) iquad, real, intent(in) xi, real, intent(in) eta)
Parameters
iquad,: quadrangle element number in cpu myrank
xi : \(\xi \) local coordinate where to compute global coordinates
eta : \(\eta\) local coordinate where to compute global coordinates
Definition at line 272 of file module_coordinate.f90.
References mod_lagrange::lagrap_geom().
Referenced by mod_receiver::compute_info_quad_receiver().
The documentation for this module was generated from the following file:
module_coordinate.f90