efispec.f90 File Reference
efispec.f90 File Reference
This file contains the main spectral finite element program: EFISPEC3D.
Functions/Subroutines
program efispec3d
Detailed Description
This program is composed by :
an initialization phase;
a time loop;
a finalization phase.
Definition in file efispec.f90.
Function/Subroutine Documentation
program efispec3d ()
Returns
void
Definition at line 116 of file efispec.f90.
References mod_mpi_assemble::assemble_force_async_comm_end(), mod_mpi_assemble::assemble_force_async_comm_init(), mod_mpi_assemble::assemble_force_sync_comm(), mod_solver::compute_absorption_forces(), mod_source::compute_double_couple_source(), mod_solver::compute_external_force(), mod_solver::compute_internal_forces_order4(), mod_solver::compute_internal_forces_order5(), mod_solver::compute_internal_forces_order6(), mod_source::init_double_couple_source(), mod_init_efi::init_gll_nodes(), mod_init_efi::init_gll_nodes_coordinates(), mod_init_medium::init_hexa_medium(), mod_receiver::init_hexa_receiver(), mod_init_efi::init_input_variables(), mod_init_efi::init_jacobian_matrix_hexa(), mod_init_efi::init_jacobian_matrix_quad(), mod_init_efi::init_mass_matrix(), mod_init_mesh::init_mesh(), mod_init_efi::init_mpi(), mod_init_mpibuffer::init_mpi_buffers(), mod_receiver::init_quad_receiver(), mod_init_medium::init_quadp_medium(), mod_source::init_single_force_source(), mod_snapshot::init_snapshot(), mod_init_memory::memory_consumption(), mod_solver::newmark_end(), mod_solver::newmark_ini(), mod_snapshot::write_collection_vtk(), mod_snapshot::write_peak_ground_motion(), mod_receiver::write_receiver_output(), and mod_snapshot::write_snapshot().